<?php 

define("DATABASE_DIR", ROOT_DIR . DIRECTORY_SEPARATOR . "database" . DIRECTORY_SEPARATOR);
define("TEMPLATES_DIR", ROOT_DIR . DIRECTORY_SEPARATOR . "templates" . DIRECTORY_SEPARATOR);
define("FUNCTIONS_DIR", ROOT_DIR . DIRECTORY_SEPARATOR . "fn" . DIRECTORY_SEPARATOR);
